"""
demo.py — Narrated walkthrough of the UCLA CS Unofficial Guide RAG system.

Covers:
  1. Three queries with source citations visible
  2. One query where retrieval + generation work well
  3. One query where the system struggles (with explanation)
  4. Evaluation report summary

Run: python demo.py
"""

import textwrap
from query import ask
from embed import retrieve

W = 65  # line width for formatting


def rule(char="─"):
    print(char * W)


def header(title):
    print()
    rule("═")
    print(f"  {title}")
    rule("═")


def section(title):
    print()
    rule()
    print(f"  {title}")
    rule()


def narrate(text):
    """Print narrator commentary in a visually distinct style."""
    wrapped = textwrap.fill(text, width=W - 4)
    for line in wrapped.splitlines():
        print(f"  ▶  {line}")


def show_query(label, query, note=None):
    print(f"\n  Query: \"{query}\"")
    if note:
        narrate(note)
    print()
    result = ask(query)
    # Answer — wrapped
    for line in textwrap.fill(result["answer"], width=W - 2).splitlines():
        print(f"  {line}")
    print()
    print(result["sources"])
    # Distances
    print("\n  Retrieval distances:")
    for i, c in enumerate(result["chunks"], 1):
        bar = "█" * int((1 - c["distance"]) * 20)
        print(f"    [{i}] {c['distance']:.3f}  {bar:<20}  {c['source']}")


# ─────────────────────────────────────────────────────────────────────────────
header("UCLA CS UNOFFICIAL GUIDE  —  RAG Demo")
narrate(
    "This system answers questions about UCLA CS professors and courses "
    "using 517 chunks from 11 Bruinwalk review files. Every answer is "
    "grounded in retrieved text — the model cannot add facts that aren't "
    "in the sources. Source attribution is appended programmatically, not "
    "generated by the LLM."
)

# ─────────────────────────────────────────────────────────────────────────────
header("PART 1 — Three queries with source citations")

section("Query 1 of 3")
show_query(
    "Q1",
    "What lecture format does Professor Reinman use in CS33?",
)

section("Query 2 of 3")
show_query(
    "Q2",
    "What are students' biggest complaints about Eggert's exams?",
)

section("Query 3 of 3")
show_query(
    "Q3",
    "Does Professor Tamir curve grades in CSM151B?",
)

# ─────────────────────────────────────────────────────────────────────────────
header("PART 2 — Query where retrieval and generation both work well")

section("Best-case query")
narrate(
    "This query targets a topic with dense, specific coverage in the corpus. "
    "Watch for low distance scores (below 0.40) and an answer that cites "
    "concrete details — exam averages, specific advice — traceable directly "
    "to the retrieved text."
)
show_query(
    "GOOD",
    "What are students' biggest complaints about Eggert's courses?",
    note=(
        "This topic has dense, specific coverage across multiple files. "
        "Expect distances under 0.35 and an answer that cites concrete "
        "details — exam averages, workload figures — traceable directly "
        "to the retrieved text."
    ),
)

# ─────────────────────────────────────────────────────────────────────────────
header("PART 3 — Query where the system struggles")

section("Failure case")
narrate(
    "This query asks about 'introductory programming' — CS31 and CS32 at UCLA. "
    "Those courses are not in the corpus. Watch what happens: the retriever "
    "returns the closest semantic match it can find (CS111, CS131), and the "
    "model either refuses or draws a wrong inference from off-target chunks."
)
show_query(
    "FAIL",
    "Which UCLA CS professor is most recommended for introductory programming?",
)
print()
narrate(
    "ROOT CAUSE — Retrieval stage: CS31 and CS32 have no documents in the "
    "corpus. The retriever matched on 'programming' and 'recommended' across "
    "all files, returning CS111 (operating systems) as the nearest hit. "
    "If the model cited Eggert for CS111 as 'introductory programming,' that "
    "is a category error — the system prompt prevents hallucination but cannot "
    "prevent the model from misapplying a retrieved fact to the wrong context."
)
narrate(
    "FIX: Add a distance threshold — if the top result exceeds 0.45, return "
    "the refusal response rather than passing weak chunks to the LLM."
)

# ─────────────────────────────────────────────────────────────────────────────
header("PART 4 — Evaluation report summary")

narrate("Six questions were tested. Results:")
print()

rows = [
    ("Q1", "CS31 difficulty",            "✓ Correct refusal",  "CS31 not in corpus — refused cleanly"),
    ("Q2", "Reinman curving grades",      "✓ Correct refusal",  "Right professor retrieved; vocab gap on 'curve'"),
    ("Q3", "CS32 complaints",            "✓ Correct refusal",  "CS32 not in corpus; distances 0.41–0.47"),
    ("Q4", "Office hours vs TAs",        "~ Partial",          "Weak retrieval (dist >0.50); one off-topic chunk"),
    ("Q5", "Most recommended professor", "✗ Grounding failure","Misread CS111 as 'introductory programming'"),
    ("Q6", "Nacherberg project (refusal)","✓ Correct refusal", "Retrieval vocab mismatch; refused vs. hallucinating"),
]

print(f"  {'#':<4} {'Topic':<30} {'Result':<22} {'Notes'}")
print(f"  {'─'*4} {'─'*30} {'─'*22} {'─'*20}")
for r in rows:
    print(f"  {r[0]:<4} {r[1]:<30} {r[2]:<22} {r[3]}")

print()
narrate(
    "Key finding: the refusal mechanism works — the model never fabricated "
    "an answer when retrieved chunks were weak or off-topic (Q1, Q2, Q3, Q6). "
    "The one genuine failure (Q5) occurred when retrieved chunks were plausible "
    "but semantically off-target, and the model drew a wrong inference rather "
    "than refusing. Grounding prevents hallucination; it does not prevent "
    "misapplication of retrieved facts."
)
print()
rule("═")
print("  End of demo.")
rule("═")
print()
