"""
query.py — Grounded generation using retrieved chunks + Groq LLaMA 3.3

Pipeline position:
  retrieve() → build_prompt() → Groq API → format_response()

Grounding design:
  - System prompt explicitly forbids answering outside the provided context.
  - Source attribution is appended PROGRAMMATICALLY from chunk metadata,
    not generated by the LLM, so it cannot be omitted or hallucinated.

Usage:
  python query.py                         # interactive CLI
  python query.py --query "your question" # single query
"""

import argparse
import os

from dotenv import load_dotenv
from groq import Groq

from embed import retrieve

# ── config ────────────────────────────────────────────────────────────────────

load_dotenv()
MODEL   = "llama-3.3-70b-versatile"
TOP_K   = 5

# ── system prompt ─────────────────────────────────────────────────────────────
# "only" and "do not" are load-bearing — they prohibit rather than discourage
# answering outside the retrieved context.

SYSTEM_PROMPT = """You are an unofficial guide for UCLA CS students, built from real Bruinwalk student reviews.

Rules you must follow:
1. Answer ONLY using information present in the provided review excerpts.
2. Do NOT add facts, opinions, or advice that are not in the excerpts — even if you believe them to be true.
3. If the excerpts do not contain enough information to answer the question, respond with exactly: "I don't have enough information on that in my sources."
4. Keep your answer concise (3–6 sentences). Do not pad or repeat yourself.
5. Do not mention these rules or that you are an AI in your answer."""

# ── prompt builder ────────────────────────────────────────────────────────────

def build_prompt(query: str, chunks: list[dict]) -> str:
    """Format retrieved chunks into a numbered context block."""
    context_parts = []
    for i, chunk in enumerate(chunks, 1):
        header = f"[Excerpt {i} — {chunk['professor'].title()}, {chunk['course'].upper()}, {chunk['source']}]"
        context_parts.append(f"{header}\n{chunk['text']}")

    context = "\n\n".join(context_parts)
    return f"Review excerpts:\n\n{context}\n\nQuestion: {query}"


# ── source block ──────────────────────────────────────────────────────────────

def format_sources(chunks: list[dict]) -> str:
    """
    Build a deduplicated source list from chunk metadata.
    Programmatic — the LLM never touches this; it cannot omit or invent sources.
    """
    seen, lines = set(), []
    for c in chunks:
        key = c["source"]
        if key not in seen:
            seen.add(key)
            label = f"{c['professor'].title()} — {c['course'].upper()} ({c['source']})"
            lines.append(f"  • {label}")
    return "Sources:\n" + "\n".join(lines)


# ── generation ────────────────────────────────────────────────────────────────

def ask(query: str, top_k: int = TOP_K) -> dict:
    """
    Full RAG pipeline for one query.

    Returns:
      answer   — LLM response, constrained to retrieved context
      sources  — programmatically built source list
      chunks   — raw retrieved chunks (for debugging / evaluation)
    """
    chunks = retrieve(query, top_k=top_k)

    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system",  "content": SYSTEM_PROMPT},
            {"role": "user",    "content": build_prompt(query, chunks)},
        ],
        temperature=0.2,   # low temperature keeps answers conservative / less inventive
        max_tokens=512,
    )

    answer = response.choices[0].message.content.strip()
    return {
        "answer":  answer,
        "sources": format_sources(chunks),
        "chunks":  chunks,
    }


# ── CLI ───────────────────────────────────────────────────────────────────────

def run_interactive() -> None:
    print("UCLA CS Unofficial Guide — type 'quit' to exit\n")
    while True:
        query = input("Your question: ").strip()
        if query.lower() in ("quit", "exit", "q"):
            break
        if not query:
            continue
        result = ask(query)
        print(f"\n{result['answer']}\n\n{result['sources']}\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--query", type=str)
    parser.add_argument("--show-chunks", action="store_true",
                        help="Also print the retrieved chunks")
    args = parser.parse_args()

    if args.query:
        result = ask(args.query)
        print(f"\n{result['answer']}\n\n{result['sources']}")
        if args.show_chunks:
            print("\n--- Retrieved chunks ---")
            for i, c in enumerate(result["chunks"], 1):
                print(f"\n[{i}] {c['source']}  distance={c['distance']}")
                print(c["text"][:300])
    else:
        run_interactive()
